# The below option makes Vaelzan very sad. :(
"Creeper explosions destroy blocks" = true
"Creeper explosions spawn creepies" = true
"Creepers drop Creeper Spores after they die from an explosion" = true

